# Generated by Django 4.1.1 on 2022-09-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('nota', models.PositiveIntegerField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
